Fix big-int vs. float bug due to missing type in codegen
I noticed this when I fixed the error about the float type:
```
gengnerated/src/Types.gen.ts:8:82 - error TS2307: Cannot find module './GqlDbCustomTypes.gen' or its corresponding type declarations.
8 import type {Float_dbNumericFloat as GqlDbCustomTypes_Float_dbNumericFloat} from './GqlDbCustomTypes.gen';
```

Forgot to make the patch last night.